### ISSUE TITLE
Generate a .gitignore

### ISSUE THREAD

**Issue by agguillemot** [thetribeio/generator-project#687] opened 2021-11-17 16:11 UTC
Generate a .gitignore at the root of the generated project so that the first commit is not polluted with unwanted generated files (like node_modules)

**Comment by jvasseur** [comment] 2021-11-17 16:57
This is a duplicate of #565 that was fixed by #570 and will be in the next release (soon).

**Closed by jvasseur** 2021-11-17 16:57 UTC
